# Generated by Django 3.1.7 on 2021-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210422_1339'),
        ('work', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
