# Generated by Django 3.1.7 on 2021-05-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210523_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس الکترونیکی')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='مقالات')),
            ],
        ),
    ]
