# Generated by Django 3.1.7 on 2021-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210524_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمل')),
                ('address', models.TextField(verbose_name='آدرس شرکت')),
                ('social_face', models.URLField(max_length=250, verbose_name='فیسبوک')),
                ('social_twitter', models.URLField(max_length=250, verbose_name='تویتتر')),
                ('social_telegram', models.URLField(max_length=250, verbose_name='تلگرام')),
                ('social_inestagram', models.URLField(max_length=250, verbose_name='انیستاگرام')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='لوگو')),
                ('about_us', models.TextField(verbose_name='درمورد ما')),
                ('time', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('face_pic1', models.ImageField(upload_to='face_pic', verbose_name='1تصویر فیسبوک')),
                ('face_pic2', models.ImageField(upload_to='face_pic', verbose_name='2تصویر فیسبوک')),
                ('face_pic3', models.ImageField(upload_to='face_pic', verbose_name='3تصویر فیسبوک')),
                ('face_pic4', models.ImageField(upload_to='face_pic', verbose_name='4تصویر فیسبوک')),
                ('face_pic5', models.ImageField(upload_to='face_pic', verbose_name='5تصویر فیسبوک')),
                ('face_pic6', models.ImageField(upload_to='face_pic', verbose_name='6تصویر فیسبوک')),
            ],
        ),
    ]
