# Generated by Django 3.1.7 on 2021-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='social_face',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='all',
            name='social_inestagram',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='انیستاگرام'),
        ),
        migrations.AlterField(
            model_name='all',
            name='social_telegram',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='all',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='تویتتر'),
        ),
    ]
