# Generated by Django 3.1.7 on 2021-05-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210526_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All',
            new_name='Alls',
        ),
    ]
