# Generated by Django 3.1.7 on 2021-05-29 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210529_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='alls',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
