# Generated by Django 3.1.7 on 2021-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_alls_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='alls',
            name='map_area',
            field=models.URLField(blank=True, max_length=300, verbose_name='گوگل مپ'),
        ),
    ]
