# Generated by Django 3.1.7 on 2021-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_our_service_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='main',
            name='images',
        ),
        migrations.RemoveField(
            model_name='main',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='main',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tiwitter',
        ),
        migrations.RemoveField(
            model_name='main',
            name='youtube',
        ),
    ]
