# Generated by Django 3.1.7 on 2021-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default=True, null=True, upload_to='video'),
        ),
    ]
