# Generated by Django 3.1.7 on 2021-04-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_hestory_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hestory',
            name='yeras',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
    ]
