# Generated by Django 3.1.7 on 2021-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_auto_20210429_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_service',
            name='pic_why',
            field=models.ImageField(null=True, upload_to='service'),
        ),
    ]
