# Generated by Django 3.1.7 on 2021-04-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_our_service_pic_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('detail', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='feature')),
            ],
        ),
        migrations.RemoveField(
            model_name='our_service',
            name='pic_why',
        ),
        migrations.RemoveField(
            model_name='our_service',
            name='why_content',
        ),
        migrations.RemoveField(
            model_name='our_service',
            name='why_name',
        ),
    ]
