# Generated by Django 3.1.7 on 2021-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_auto_20210430_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
